COMPILER = g++
FLAGS = -g3 -Wall -Werror -Wextra -Wpedantic -std=c++17
EXECUTABLE = async_logger.exe
SOURCES = main.cpp
OBJECTS = $(SOURCES:.cpp=.o)

$(EXECUTABLE):
	$(COMPILER) $(FLAGS) -c main.cpp
	$(COMPILER) -o $(EXECUTABLE) $(OBJECTS)
	powershell.exe -Command "./$(EXECUTABLE)"
