COMPILER = g++
FLAGS = -g -Wall -std=c++17

SOURCES = main.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = async_logger.exe

TEST_SOURCE = queue_test.cpp
TEST_OBJECTS = $(TEST_SOURCE:.cpp=.o)
TEST_EXECUTABLE = $(TEST_SOURCE:.cpp=.exe)

all: $(EXECUTABLE)

test:
	$(COMPILER) $(FLAGS) -c $(TEST_SOURCE)
	$(COMPILER) -o $(TEST_EXECUTABLE) $(TEST_OBJECTS)
	powershell.exe -Command "./$(TEST_EXECUTABLE)"

$(EXECUTABLE): $(OBJECTS)
	$(COMPILER) $(FLAGS) $@ $<

$(OBJECTS): $(SOURCES)
	$(COMPILER) $(FLAGS) -c $<
